import bpy

for shapekey in bpy.data.shape_keys:
    # rename / translate shape key names by changing shapekey.name
    for keyblock in shapekey.key_blocks:
        
        print ("Now processing... ")
        print (keyblock.name)
        
        if keyblock.name == "A01_Brow_Inner_Up": keyblock.name = "browInnerUp"
        if keyblock.name == "A02_Brow_Down_Left": keyblock.name = "browDownLeft"
        if keyblock.name == "A03_Brow_Down_Right": keyblock.name = "browDownRight"
        if keyblock.name == "A04_Brow_Outer_Up_Left": keyblock.name = "browOuterUpLeft"
        if keyblock.name == "A05_Brow_Outer_Up_Right": keyblock.name = "browOuterUpRight"
        if keyblock.name == "A06_Eye_Look_Up_Left": keyblock.name = "eyeLookUpLeft"
        if keyblock.name == "A07_Eye_Look_Up_Right": keyblock.name = "eyeLookUpRight"
        if keyblock.name == "A08_Eye_Look_Down_Left": keyblock.name = "eyeLookDownLeft"
        if keyblock.name == "A09_Eye_Look_Down_Right": keyblock.name = "eyeLookDownRight"
        if keyblock.name == "A10_Eye_Look_Out_Left": keyblock.name = "eyeLookOutLeft"
        if keyblock.name == "A11_Eye_Look_In_Left": keyblock.name = "eyeLookInLeft"
        if keyblock.name == "A12_Eye_Look_In_Right": keyblock.name = "eyeLookInRight"
        if keyblock.name == "A13_Eye_Look_Out_Right": keyblock.name = "eyeLookOutRight"
        if keyblock.name == "A14_Eye_Blink_Left": keyblock.name = "eyeBlinkLeft"
        if keyblock.name == "A15_Eye_Blink_Right": keyblock.name = "eyeBlinkRight"
        if keyblock.name == "A16_Eye_Squint_Left": keyblock.name = "eyeSquintLeft"
        if keyblock.name == "A17_Eye_Squint_Right": keyblock.name = "eyeSquintRight"
        if keyblock.name == "A18_Eye_Wide_Left": keyblock.name = "eyeWideLeft"
        if keyblock.name == "A19_Eye_Wide_Right": keyblock.name = "eyeWideRight"
        if keyblock.name == "A20_Cheek_Puff": keyblock.name = "cheekPuff"
        if keyblock.name == "A21_Cheek_Squint_Left": keyblock.name = "cheekSquintLeft"
        if keyblock.name == "A22_Cheek_Squint_Right": keyblock.name = "cheekSquintRight"
        if keyblock.name == "A23_Nose_Sneer_Left": keyblock.name = "noseSneerLeft"
        if keyblock.name == "A24_Nose_Sneer_Right": keyblock.name = "noseSneerRight"
        if keyblock.name == "A25_Jaw_Open": keyblock.name = "--DeleteThis--"
        if keyblock.name == "A26_Jaw_Forward": keyblock.name = "jawForward"
        if keyblock.name == "A27_Jaw_Left": keyblock.name = "jawLeft"
        if keyblock.name == "A28_Jaw_Right": keyblock.name = "jawRight"
        if keyblock.name == "A29_Mouth_Funnel": keyblock.name = "mouthFunnel"
        if keyblock.name == "A30_Mouth_Pucker": keyblock.name = "mouthPucker"
        if keyblock.name == "A31_Mouth_Left": keyblock.name = "mouthLeft"
        if keyblock.name == "A32_Mouth_Right": keyblock.name = "mouthRight"
        if keyblock.name == "A33_Mouth_Roll_Upper": keyblock.name = "mouthRollUpper"
        if keyblock.name == "A34_Mouth_Roll_Lower": keyblock.name = "mouthRollLower"
        if keyblock.name == "A35_Mouth_Shrug_Upper": keyblock.name = "mouthShrugUpper"
        if keyblock.name == "A36_Mouth_Shrug_Lower": keyblock.name = "mouthShrugLower"
        if keyblock.name == "A37_Mouth_Close": keyblock.name = "mouthClose"
        if keyblock.name == "A38_Mouth_Smile_Left": keyblock.name = "mouthSmileLeft"
        if keyblock.name == "A39_Mouth_Smile_Right": keyblock.name = "mouthSmileRight"
        if keyblock.name == "A40_Mouth_Frown_Left": keyblock.name = "mouthFrownLeft"
        if keyblock.name == "A41_Mouth_Frown_Right": keyblock.name = "mouthFrownRight"
        if keyblock.name == "A42_Mouth_Dimple_Left": keyblock.name = "mouthDimpleLeft"
        if keyblock.name == "A43_Mouth_Dimple_Right": keyblock.name = "mouthDimpleRight"
        if keyblock.name == "A44_Mouth_Upper_Up_Left": keyblock.name = "mouthUpperUpLeft"
        if keyblock.name == "A45_Mouth_Upper_Up_Right": keyblock.name = "mouthUpperUpRight"
        if keyblock.name == "A46_Mouth_Lower_Down_Left": keyblock.name = "mouthLowerDownLeft"
        if keyblock.name == "A47_Mouth_Lower_Down_Right": keyblock.name = "mouthLowerDownRight"
        if keyblock.name == "A48_Mouth_Press_Left": keyblock.name = "mouthPressLeft"
        if keyblock.name == "A49_Mouth_Press_Right": keyblock.name = "mouthPressRight"
        if keyblock.name == "A50_Mouth_Stretch_Left": keyblock.name = "mouthStretchLeft"
        if keyblock.name == "A51_Mouth_Stretch_Right": keyblock.name = "mouthStretchRight"
        if keyblock.name == "A52_Tongue_Out": keyblock.name = "tongueOut"
        if keyblock.name == "Merged_Open_Mouth": keyblock.name = "jawOpen"
        
        print ("All done!")
